# Generated by Django 5.0 on 2025-06-20 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('chordpro', models.FileField(upload_to='')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='search.source')),
            ],
        ),
    ]
