# Generated by Django 5.0 on 2025-06-29 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='main_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='search.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='chordpro',
            field=models.FileField(unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
