# Generated by Django 5.0 on 2025-06-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_song_main_version_alter_song_chordpro_alter_song_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='chordpro',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=''),
        ),
    ]
