# Generated by Django 5.0 on 2025-07-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_song_chordpro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='chordpro',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
