# Generated by Django 5.0 on 2026-01-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_song_chordpro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.URLField(),
        ),
    ]
